### ISSUE TITLE
Allow custom CSS for HintMarker for font-size and so on

### ISSUE THREAD

**Issue by fanckush** [televator-apps/vimari#161]
Is there a way to change the styles of the markers?
I personally need a bigger font as I have trouble with reading the small letters on the markers

**Comment by translit** [comment]
Not to mention that that yellow always sucked.

**Comment by fanckush** [comment]
@translit you can add a custom style sheet to be loaded on every page in order to override the styles that you want to change
Go to preferences->advanced and then you'll see a dropdown to select a .css file.

**Comment by eproxus** [comment]
@fanckush This is in fact not possible (Safari 15.1 [17612.2.9.1.20]). The style sheet from Vimari somehow has priority over the custom style sheet.

<img width="300" alt="Screen Shot 2021-11-15 at 15 15 30" src="https://user-images.githubusercontent.com/112878/141796893-85e0abae-3fa8-4b16-af13-2b5ce9162b1d.png">

I would like this feature as well (either via setting or via a custom style sheet.

**Comment by fanckush** [comment]
@eproxus how about adding more priority to your added CSS such as:
``` css
* div.intervalVimumHintMarker { ... }
```

**Comment by eproxus** [comment]
@fanckush After trying that _and_ adding `!important` to every property it works. Note that Safari doesn't seem to pick up the changes on every save of the CSS file _nor_ on every page load. My results are only visible now after a restart and some page loads... Can't figure out the heuristic. 😄

Luckily it works in the end, so I think this "workaround" is good enough.

For anyone interested, here's how to achieve custom styling:

1. Create a `stylesheet.css` somewhere on disk with some content. E.g. the styles from Chromium:
   ```css
   * div.internalVimiumHintMarker {
     font-size: 11px !important;
     padding: 1px 3px 0px 3px !important;
     background: linear-gradient(to bottom, #FFF785 0%,#FFC542 100%) !important;
     border: solid 1px #C38A22 !important;
     border-radius: 3px !important;
     box-shadow: 0px 3px 7px 0px rgba(0, 0, 0, 0.3) !important;
   }
   
   * div.internalVimiumHintMarker span {
     color: #302505 !important;
     font-family: Helvetica, Arial, sans-serif !important;
     font-weight: bold !important;
     font-size: 11px !important;
     text-shadow: 0 1px 0 rgba(255, 255, 255, 0.6) !important;
   }
   
   * div.internalVimiumHintMarker > .matchingCharacter {
     color: #D4AC3A !important;
   }
   
   * div > .vimiumActiveHintMarker span {
     color: #A07555 !important;
   }
   ```
2. In Safari, go to _Preferences_ → _Advanced_ → _Style sheet_ → _Other..._ and select your file.
3. Restart Safari (I'd appreciate some experimentation from others here to figure out exactly what is required)
